[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
simple_amm = "4BZvwNrG5SdK3DV5uctRqNKveRbReW3hCyZwKjeWZ7ua"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/edwardpavlovsky/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
